init plugin
afdesk/trivy-gitlab pull request #1
Opened 2023-04-10 14:21 UTC by nikpivkin

2023-04-26 09:19 UTC, afdesk requested changes

2023-04-26 09:19 UTC, afdesk commented on Makefile
do we really need this Makefile here?

2023-04-26 09:19 UTC, afdesk commented on cmd/trivy-gitlab/main.go
> +}
why do we need this function?

2023-04-26 09:19 UTC, afdesk commented on go.mod
> +go 1.20
let's use 1.19

2023-04-27 06:07 UTC, nikpivkin commented on go.mod
> +go 1.20
done

2023-04-28 12:28 UTC, merged